### ISSUE TITLE
Избегай явного указания точек доступа

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#13]
https://github.com/J3olchara/yandex_django/blob/2198effa5efcd50f84117039e31f52b654ee80c9/lyceum/homepage/tests.py#L8

- В реальных проектах довольно часто меняются точки доступа (url пути) в отличие от их имён, reverse + имя пути помогает избежать ошибок при смене направлений, да и в коде читается лучше ("home" вместо неинформативного "/")

**Comment by J3olchara** [comment]
сделал)
