### ISSUE TITLE
Тест не полный

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#15]
https://github.com/J3olchara/yandex_django/blob/2198effa5efcd50f84117039e31f52b654ee80c9/lyceum/lyceum/tests.py#L29

- А где проверка, что переворот происходит раз в n запросов? :) 
- Проверка, что "переворот" слов происходит за счёт именно этого middleware - это хорошо, но, вот, работа переменной окружения не протестирована. И, забегая вперёд, подскажу, что проверить её внутри setting'a будет гораздо сложнее, чем если сделать проверку внутри метода класса (достаточно импортировать её из сеттинга, а на тесте отключить её декоратором из unittest'а).

**Comment by J3olchara** [comment]
дополнил тест
