### ISSUE TITLE
Лишние зависимости

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#2]
https://github.com/J3olchara/yandex_django/blob/8d3b4eedff0ff1b346733ce3929add1dacdc3e62/requirements.txt#L3

- Наравне с чистотой кода важна и чистота зависимостей. Здесь должны указывать только те приложения, которые используются в проекте. Также замечу, что не следует указывать зависимости, которые ставятся совместно с другими зависимостями. Хорошая практика - прежде, чем что-то установить для проекта: pip install some_libruary, внести её в requirements (или сразу после) и прежде, чем удалить библиотеку - удалить её зависимость.

**Comment by J3olchara** [comment]
Почистил файлики от зависимостей зависимостей, больше pip freeze не буду юзать))
