### ISSUE TITLE
Малоинформативный readme

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#3]
https://github.com/J3olchara/yandex_django/blob/8d3b4eedff0ff1b346733ce3929add1dacdc3e62/README.md

- Нет описания по работе с .env файлом.
- В целом задание, кроме описания про .env файл, выполнено, но на будущее рекомендую уделять readme больше внимания - структурирование, ветвление (на разные системы, условия запуска и т.д.) - это всегда полезно для работы.

**Comment by J3olchara** [comment]
вроде всё сделал, добавил описание про .env файл и сделал мануал запуска на линуксе (насколько мне известно вроде на всех линуксах будь то убунту или дебиан оно всё одинаково работает)
