### ISSUE TITLE
.env в репозитории

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#4]
https://github.com/J3olchara/yandex_django/blob/8d3b4eedff0ff1b346733ce3929add1dacdc3e62/.env#L1

- Основной смысл .env файлов - это то, чтобы они хранились только на сервере (компьютере), где они будут запускаться, чтобы никто не смог получить к ним доступ. Если необходимо добавить информацию по созданию .env файла, добавь её в README.md и добавь при желании .env-example для примера.

**Comment by J3olchara** [comment]
сделал example.env и добавил инструкцию о .env в readme.md
