### ISSUE TITLE
Стартовые (учебные) комментарии

### ISSUE THREAD

**Issue by Danielseddian** [J3olchara/yandex_django#5]
https://github.com/J3olchara/yandex_django/blob/8d3b4eedff0ff1b346733ce3929add1dacdc3e62/lyceum/lyceum/wsgi.py#L1-L8

- Здесь и в других местах, где при генерации проекта добавлены базовые комментарии, необходимо их удалить. Есть понятия "чистота кода" и "необходимый минимум". Эти комментарии помогают начинающему разработчику разобраться с приложением (Django), определить где и что находится, а также добавляют ссылки на официальную документацию, но абсолютно бесполезны при поддержании и развитии проекта. Комментарии нужны и полезны, особенно, когда меняешь работу базовых функций и классов или добавляешь многоуровневый код, но добавлять их к каждой строчке кода - избыточно и не нужно. Лучше добавь ссылку на документацию Django в README.md

**Comment by J3olchara** [comment]
Сделал
